### PR TITLE
watermark visualizations

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR will add watermark/overlay image to visualization:
charts

To test:
1. update variable `applyWatermark = false;` and set the value to true.
in file: js/tripalD3.watermark.js

2. change `watermark.png` image in css/ to desired file but ensure to use the same filename.

3. update list in dir variable in tripalD3Watermark() function located in js/tripalD3.watermark.js.
To add:
If Tripald3 is implemented in this page `mysite.com/coolcharts/awesomegene.php`, add the keyword `coolcharts` to the array dir.

4. save
5. clear cache
6. reload page

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Tripal D3 is meant to be an API used by other extension modules. For example, Tripal Fancy Fields uses this API extensively for it's diagrams. For the watermark, ideally there would be an API function that a developer can call to add a watermark to any SVG. For example,

```js
tripalD3.drawFigure(data, { 
  'elementId' => 'my-awesome-chart',
  \\ additional chart options here
});

tripalD3.addWatermark({
  'elementId' => 'my-awesome-chart',
  'image' => '/full/path/to/image/for/watermark.png',
});
```

In this way, a developer can easily use the API to add a watermark to any svg/div without having to edit our module.

To add to the API in this manner, your function would use the same format as [tripald3/js/tripalD3.pie.js](https://github.com/tripal/tripald3/blob/7.x-1.x/js/tripalD3.pie.js). For example,

```js
tripalD3.addWatermark = {
   // code to be executed immediately...

   // Any helper functions you need
   helperfunction1: function (param1, param1) {

   },
   helperfunction2: function () {

   },
};
```

**Comment by reynoldtan** [comment]
I have revised API to watermark diagrams and included a section in demo page to show an example.
Screen Shot 2019-04-12 at 3 16 57 PM (2)

To use:
Simply call the function tripalD3.placeWatermark() after tripalD3.drawFigre() call.
Example:

`tripalD3.drawFigure(chartdata, {chart parameters});`
`tripalD3.placeWatermark(); `

By default, this method will stamp the image set in the css/watermark.png directory. This can be replaced with the ideal image for a unified watermark. 

To customize watermark for chart in one page to a diagram in another page, provide a path to a watermark image to the function.
Example:

`tripalD3.drawFigure(chartdata, {chart parameters});`
`tripalD3.placeWatermark({'watermark' : 'http://mysite.ca/images/logotype.png'});`

**Review by laceysanderson — APPROVED** [review]
This PR works perfectly :-) 

However, it requires an update to the documentation. Please add the "To use" instructions from the PR to https://tripal-d3js-api.readthedocs.io/en/latest/ using RST in the `docs/` directory.

**Comment by laceysanderson** [comment]
Merging as it it needed to fix a partial commit on master. The request for documentation has been added to the parent issue.

**Pull request merged**
